// Code generated by "stringer -type=ServiceState"; DO NOT EDIT.

package svc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceState_Idle-0]
	_ = x[ServiceState_Init-1]
	_ = x[ServiceState_Config-2]
	_ = x[ServiceState_Ready-3]
	_ = x[ServiceState_Migrate-4]
	_ = x[ServiceState_Running-5]
	_ = x[ServiceState_Pause-6]
	_ = x[ServiceState_Destroy-7]
}

const _ServiceState_name = "ServiceState_IdleServiceState_InitServiceState_ConfigServiceState_ReadyServiceState_MigrateServiceState_RunningServiceState_PauseServiceState_Destroy"

var _ServiceState_index = [...]uint8{0, 17, 34, 53, 71, 91, 111, 129, 149}

func (i ServiceState) String() string {
	if i < 0 || i >= ServiceState(len(_ServiceState_index)-1) {
		return "ServiceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceState_name[_ServiceState_index[i]:_ServiceState_index[i+1]]
}
